spring:
  codec:
    max-in-memory-size: 50MB
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            allow-credentials: true
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowedOriginPatterns: ".*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedMethods: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: api
          uri: http://gongkao6688.edudisk.cn/
          predicates:
            - Path=/**
            #- Header=host,([a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+)
            #- Header=my-host,(.*)
            #filters:
            #- StripPrefix=1
      httpclient:
        ssl:
          use-insecure-trust-manager: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
    time-zone: GMT+8
  redis:
    port: 6379
    host: 127.0.0.1

server:
  port: 10090
#spring boot actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
project:
  gateway:
    log-response: false